-- Português --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(1,1,'Alfabetização','O processo de alfabetização é quando a criança aprende a reconhecer as letras, os sons (fonemas) que elas representam e a formar palavras. Explica-se como cada letra se pronuncia, apresenta-se o alfabeto, sílabas simples (ex.: ma, me, mi, mo, mu) e a junção dessas sílabas para formar palavras (ex.: ma + pa = mapa). Objetivos: identificar letras, relacionar som e grafia, escrever palavras simples. Exemplos: ler palavras como "sol", "mãe" e "casa". Exercícios: 1) Diga as letras do alfabeto em voz alta; 2) Separe a palavra "banana" em sílabas; 3) Escreva três palavras que comecem com a letra "c".'),
(1,1,'Formação de palavras','Estudo de como as palavras são construídas a partir de sílabas e letras e como elas se agrupam em classes simples (nome, ação, objeto). Explica-se sílabas abertas e fechadas (ex.: "ca" é aberta; "sol" é fechada) e mostra-se como juntar sílabas para formar palavras. Introduzem-se noções simples de radical e sufixo com exemplos fáceis (ex.: "flor" + "inha" = "florinha"). Objetivos: segmentar palavras em sílabas, criar novas palavras combinando sílabas e reconhecer padrões. Exemplos: formar "pa + pel" = "papel"; "ca + sa" = "casa". Exercícios: 1) Separe em sílabas: "amigo", "pipoca"; 2) Forme 5 palavras usando as sílabas: ma, ta, ca; 3) Identifique o radical em "casinha".'),
(1,1,'Leitura inicial','Desenvolvimento da habilidade de ler palavras e frases curtas com compreensão. Ensina-se técnicas simples: leitura silábica (ler sílaba a sílaba), identificação de palavras conhecidas e uso de imagens como apoio para entender o sentido. Trabalha-se também a habilidade de responder perguntas básicas sobre um texto (quem? o quê? onde?). Objetivos: ler frases simples, compreender ideias principais e relacionar imagens com textos. Exemplo: ler a frase "O gato bebe leite." e responder: Quem bebe? O que ele bebe? Exercícios: 1) Leia e aponte a palavra que mostra um animal em frases curtas; 2) Junte palavras para formar uma frase com sentido e desenhe a cena; 3) Leia um mini-texto e escreva a ideia principal em uma frase.'),
(1,1,'Rimas e jogos de linguagem','Atividades lúdicas que desenvolvem a consciência fonológica: identificar sons iguais no fim das palavras (rimas), brincar com parlendas, cantigas e trava-línguas. Explica-se o que é rima com exemplos (ex.: "pato" rima com "gato") e oferece-se jogos para separar sons e repeti-los. Objetivos: perceber sons iguais e diferentes nas palavras, melhorar a pronúncia e ampliar o vocabulário. Exemplos: completar pares que rimam (casa/asa, bola/cola). Exercícios: 1) Ache a palavra que rima com "sol": (bol, sol, mal) — marque a correta; 2) Crie uma pequena parlenda com palavras que rimem; 3) Jogue um jogo de "diga uma palavra que rima com..." em sala ou em casa.');

-- Matemática --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(2,1,'Números naturais','O estudo dos números naturais no 1º ano envolve reconhecer, nomear, escrever e comparar números de 0 a 20. A criança aprende a relacionar número e quantidade, contar objetos, ordenar números e identificar qual é maior ou menor. Usam-se materiais concretos como palitos, blocos, desenhos e jogos de contagem. Exemplos: contar quantos lápis há na mesa; comparar 7 e 12 (12 é maior). Exercícios: 1) Conte 15 objetos e registre o número; 2) Complete sequências numéricas como: 0, 1, 2, __, 4, 5; 3) Circule o maior número entre: 6, 14, 9.'),
(2,1,'Adição e subtração','Introdução às operações de somar e subtrair por meio de situações reais e materiais visuais. Ensina-se que somar é juntar quantidades e subtrair é tirar algo de um conjunto. São usados desenhos, blocos, dedos e histórias simples para representar problemas matemáticos. Exemplos: “João tinha 3 balas e ganhou mais 2 — quanto ele tem agora?” (3 + 2 = 5). “Ana tinha 5 brinquedos e perdeu 1 — com quantos ficou?” (5 - 1 = 4). Exercícios: 1) Resolva: 4 + 3; 2 + 2; 5 - 1; 2) Desenhe a operação 3 + 2 usando bolinhas; 3) Crie sua própria história de adição com brinquedos.'),
(2,1,'Noções de medidas','Noções iniciais de tempo, comprimento, peso e capacidade usando comparações simples do cotidiano. Ensina-se a ideia de maior/menor, mais pesado/mais leve, mais comprido/mais curto e cheio/vazio sem ainda usar unidades formais. Exemplos: comparar o tamanho de dois lápis, ver qual pote tem mais água, observar a diferença entre manhã/tarde/noite. Exercícios: 1) Compare dois objetos da sua casa e diga qual é mais pesado; 2) Coloque em ordem do mais comprido para o mais curto: régua, lápis e borracha; 3) Observe dois copos e marque qual está mais cheio. ');

-- Geografia --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(3,1,'O lugar onde vivo','O estudo do lugar onde vivo ajuda a criança a reconhecer os espaços que fazem parte do seu dia a dia: casa, escola, rua e bairro. Trabalha-se a ideia de pertencimento e observação do ambiente: como é minha casa? O que tem perto da escola? O que existe no meu bairro? Compara-se diferentes tipos de moradias, identificam-se serviços próximos (mercado, praça, farmácia) e discute-se como as pessoas utilizam e cuidam desses espaços. Exemplos: identificar caminhos percorridos até a escola, reconhecer partes da casa (quarto, sala, cozinha). Exercícios: 1) Desenhe sua casa e nomeie os cômodos; 2) Faça um desenho do caminho até a escola; 3) Liste três lugares importantes do seu bairro.'),
(3,1,'Paisagem','As paisagens são tudo aquilo que conseguimos observar ao nosso redor. No 1º ano, a criança aprende a diferenciar paisagens naturais (montanhas, rios, florestas) e paisagens modificadas pelo ser humano (casas, avenidas, praças construídas). Observa-se como as paisagens mudam com o tempo e como as pessoas interagem com elas. Ensina-se a olhar com atenção detalhes como cores, formas e elementos presentes. Exemplos: comparar uma praia (natural) com um bairro cheio de prédios (modificado). Exercícios: 1) Separe figuras em duas categorias: natural e modificada; 2) Desenhe uma paisagem natural que você conhece; 3) Observe sua rua e escreva o que nela foi construído pelo ser humano.'),
(3,1,'Mapas simples','Introdução à leitura e interpretação de mapas simples e de desenhos que representam espaços conhecidos. Ensina-se noções básicas de localização como direita/esquerda, frente/atrás, perto/longe. Trabalha-se com mapas da sala de aula, do bairro ou da escola para que a criança compreenda como os lugares podem ser representados no papel. Exemplos: localizar a posição da porta na planta da sala; identificar onde fica o parquinho no mapa da escola. Exercícios: 1) Desenhe um mapa simples da sua sala de aula; 2) Aponte no desenho o que está à direita e à esquerda da porta; 3) Marque no mapa da escola quais lugares ficam mais perto e mais longe do portão.');

-- Ciências --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(4,1,'Seres vivos','No 1º ano, a criança aprende a diferenciar seres vivos e não vivos. Explica-se que seres vivos nascem, crescem, se alimentam, respiram e podem se mover de diferentes formas, enquanto objetos não vivos não realizam essas funções. Observam-se plantas, animais e seres humanos, identificando suas características e necessidades. Exemplos: um cachorro precisa de água e comida; uma pedra não cresce nem respira. Exercícios: 1) Separe imagens em “ser vivo” e “não vivo”; 2) Liste três seres vivos que existem perto da sua casa; 3) Observe uma planta por alguns dias e registre mudanças.'),
(4,1,'Higiene','O estudo da higiene envolve aprender cuidados básicos com o corpo para manter a saúde. Ensina-se a importância de hábitos diários como lavar as mãos, escovar os dentes, tomar banho, cortar as unhas e manter roupas limpas. Explica-se como esses cuidados evitam doenças e mantêm o bem-estar. Exemplos: lavar as mãos antes das refeições, escovar os dentes após comer doces, usar sabonete no banho. Exercícios: 1) Monte uma lista de cuidados que você faz todos os dias; 2) Desenhe a forma correta de lavar as mãos; 3) Marque quais objetos são usados na higiene: escova, pasta, sabão, brinquedo.'),
(4,1,'Alimentação','A alimentação saudável é fundamental para o crescimento e a energia do corpo. A criança aprende a diferenciar alimentos naturais (frutas, verduras, legumes) e industrializados, reconhecendo quais fazem bem para a saúde. Trabalha-se a ideia de variedade alimentar e a importância de beber água. Exemplos: montar um prato colorido com frutas, experimentar novos alimentos e evitar excesso de doces. Exercícios: 1) Separe alimentos saudáveis e não saudáveis em duas colunas; 2) Desenhe seu prato saudável ideal; 3) Registre quantos copos de água você bebe em um dia.');

-- História --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(5,1,'Família','No 1º ano, o estudo da família envolve reconhecer quem faz parte dela, como cada pessoa contribui no dia a dia e como existem diferentes tipos de famílias. A criança aprende que todas as famílias são importantes e que podem ser compostas por pais, avós, irmãos, tios, responsáveis e outras combinações. Trabalha-se também a história familiar: como era a família no passado e como é hoje. Exemplos: comparar fotos antigas e atuais, conversar sobre tradições da família. Exercícios: 1) Desenhe sua família e escreva o nome de cada membro; 2) Traga uma foto antiga e conte o que mudou; 3) Liste três atividades que você faz junto com sua família.'),
(5,1,'Escola','A escola é apresentada como um espaço de convivência, aprendizagem e regras. A criança reconhece os diferentes ambientes da escola (sala de aula, pátio, biblioteca, diretoria), entende a função dos profissionais (professor, diretor, zelador, merendeira) e aprende a importância do respeito e da cooperação. Também se trabalha a rotina escolar e a história da escola: como ela funciona, para que serve e o que aprendemos nela. Exercícios: 1) Faça um desenho da sua sala de aula; 2) Escreva o nome de três profissionais da sua escola e o que eles fazem; 3) Marque quais regras você segue diariamente na escola.'),
(5,1,'Comunidade','A comunidade é o grupo de pessoas que vivem, estudam ou trabalham em um mesmo lugar. No 1º ano, o aluno aprende a importância da convivência, da ajuda mútua e do respeito aos espaços públicos. Observam-se lugares importantes da comunidade, como praças, mercados, postos de saúde e escolas. Também se discute como as pessoas colaboram para manter o ambiente organizado e seguro. Exemplos: participar de campanhas de limpeza, respeitar filas, ajudar vizinhos. Exercícios: 1) Desenhe um lugar importante da sua comunidade; 2) Liste três regras de convivência que ajudam sua comunidade; 3) Identifique quem trabalha no seu bairro e o que essas pessoas fazem.');

-- Artes --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(6,1,'Desenho','O desenho é uma forma de expressar ideias, sentimentos e imaginação. No 1º ano, a criança explora linhas, formas e detalhes simples, desenhando objetos, pessoas, animais e situações do dia a dia. Trabalha-se a observação (desenhar algo que está vendo) e o desenho livre (expressão espontânea). Exemplos: desenhar a família, a escola, um animal preferido. Exercícios: 1) Desenhe uma cena que represente um momento feliz; 2) Observe um objeto da sala e desenhe-o do seu jeito; 3) Crie um desenho apenas usando círculos, quadrados e triângulos.'),
(6,1,'Cores','As cores são estudadas por meio da identificação das cores primárias (vermelho, azul e amarelo) e das cores secundárias, criadas a partir da mistura das primárias (verde, laranja e roxo). A criança aprende como as cores podem transmitir sensações e como usá-las nas produções artísticas. Realizam-se experiências de mistura com tinta, lápis ou papel colorido. Exemplos: azul + amarelo = verde; vermelho + amarelo = laranja. Exercícios: 1) Misture tintas para criar as cores secundárias; 2) Pinte um desenho usando apenas cores frias; 3) Escolha um objeto e pinte-o com cores diferentes das reais.'),
(6,1,'Recorte e colagem','Atividades de recorte e colagem desenvolvem a coordenação motora fina, a criatividade e o cuidado com os materiais. Trabalha-se o uso correto da tesoura (sempre com segurança), recorte de formas simples e montagem de figuras combinando papéis, revistas e texturas. Também se exploram composições e criação de personagens ou cenários. Exemplos: montar um painel usando recortes de revistas, criar personagens com formas geométricas. Exercícios: 1) Recorte figuras que mostrem animais e cole formando uma paisagem; 2) Monte um desenho apenas com formas recortadas; 3) Crie um personagem usando pedaços de papel colorido.');

-- Educação Física --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(7,1,'Coordenação motora','Desenvolvimento da coordenação motora ampla e fina por meio de atividades como correr, pular, arremessar e equilibrar. O foco é ajudar a criança a reconhecer seu corpo, controlar seus movimentos e melhorar sua habilidade de se movimentar com segurança.'),
(7,1,'Brincadeiras','Exploração de jogos e brincadeiras tradicionais que ensinam regras simples, cooperação e respeito ao colega. As atividades estimulam o movimento, a criatividade e o trabalho em equipe de forma divertida.'),
(7,1,'Movimentos corporais','Descoberta e experimentação dos diferentes movimentos do corpo, como girar, rastejar, rolar e saltar. A proposta é que o aluno desenvolva consciência corporal, ritmo e domínio dos próprios movimentos.');

-- ENSINO RELIGIOSO --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(8,1,'Respeito','Estudo do valor do respeito ao próximo, às diferenças e aos espaços de convivência. O aluno aprende de forma simples e prática como atitudes respeitosas ajudam na convivência em casa, na escola e na comunidade.'),
(8,1,'Amizade','Compreensão da importância da amizade e do cuidado com os outros. As atividades incentivam o aluno a reconhecer bons comportamentos, solidariedade, empatia e a importância de ter relações saudáveis.'),
(8,1,'Família','Reflexão sobre o papel da família na vida da criança, entendendo que existem diferentes tipos de famílias. O objetivo é valorizar o afeto, o apoio, a convivência e os vínculos familiares como parte da formação dos valores pessoais.');

-- INGLÊS --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(9,1,'Alfabeto','Introdução ao alfabeto em inglês, aprendendo o nome e o som das letras por meio de músicas, imagens e atividades simples. O aluno começa a reconhecer as letras e relacioná-las a objetos do cotidiano.'),
(9,1,'Cores','Aprendizado das cores em inglês com associações visuais, brincadeiras e repetição guiada. As crianças aprendem a nomear cores básicas e identificá-las em objetos ao redor.'),
(9,1,'Números','Introdução aos números em inglês por meio de contagens simples, músicas e jogos. O foco é reconhecer, pronunciar e usar os números do 1 ao 10 de forma prática e divertida.');

-- ESPANHOL --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(10,1,'Saludos','Aprendizado dos cumprimentos básicos em espanhol, como “hola”, “adiós” e “buenos días”. As crianças praticam expressões simples usadas no cotidiano para se comunicar de forma gentil.'),
(10,1,'Colores','Exploração das cores em espanhol usando objetos, desenhos e atividades visuais. O objetivo é ensinar a identificar e pronunciar cores comuns, como rojo, azul e verde.'),
(10,1,'Números','Vocabulário inicial dos números em espanhol, com contagens de 1 a 10 feitas através de músicas, jogos e repetição oral para facilitar a memorização.');

-- FRANCÊS --
INSERT INTO tb_assuntos (materia_id, ano_id, titulo, descricao) VALUES
(11,1,'Salutations','Ensino dos cumprimentos básicos em francês, como “bonjour”, “au revoir” e “salut”. As atividades ajudam o aluno a reconhecer expressões usadas em situações simples do dia a dia.'),
(11,1,'Couleurs','Aprendizado das cores em francês através de cartões ilustrados e associações visuais. O aluno aprende a pronunciar cores básicas e identificá-las em objetos e desenhos.'),
(11,1,'Nombres','Introdução aos números em francês, com contagem de 1 a 10 usando músicas, gestos e atividades lúdicas que facilitam a fixação do vocabulário.');



